language: java
jdk:
  - openjdk11
script: ./mvnw clean install
script: ./mnvw ls

jobs:
   include:
     - stage: Test
        script: ./mvnw clean test
notifications:
  email: navyasree068@gmail.com
